imageprocessor/urls.py
from django.urls import path
from . import views

app_name = "imageprocessor"


urlpatterns = [
    path("", views.index, name="index"),
    path("upload/", views.create, name="create"),
    path("update/<int:image_id>/", views.update, name="update"),
    path("delete_image/<int:image_id>/", views.delete_image, name="delete_image"),
    path("successful/", views.success, name="success"),
    path("dashboard/", views.dashboard, name="dashboard"),
]

photo_tutorial/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("imageprocessor.urls", namespace="imageprocessor")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imageprocessor/models.py
from django.db import models
from django.urls import reverse
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill


class Image(models.Model):
    profile_pic = models.ImageField(
        upload_to="profile pic"
    )

    profile_pic_thumbnail = ImageSpecField(
        source='profile_pic',
        processors=[ResizeToFill(700, 150)],
        format="JPEG",
        options={
            'quality': 60
        }
    )

    background_pic = models.ImageField(
        upload_to="background pic"
    )

    feature_pic = models.ImageField(
        upload_to="feature pics"
    )

    def get_absolute_url(self):
        return reverse("imageprocessor:update", args=[self.id])

    @property
    def profileURL(self):
        try:
            url = self.profile_pic_thumbnail.url
        except ValueError:
            url = ''
        return url

    @property
    def backgroundURL(self):
        try:
            url_back = self.background_pic.url
        except ValueError:
            url_back = ''
        return url_back

    @property
    def featureURL(self):
        try:
            url_feature = self.feature_pic.url
        except ValueError:
            url_feature = ''
        return url_feature

imageprocessor/forms.py
from django import forms
from django.forms import fields
from .models import Image


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = "__all__"

imageprocessor/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Image
from . import forms


def index(request):

    image = Image.objects.all()
    return render(
        request, "index.html",
        dict(
            image=image
        )
    )


def create(request, *args, **kwargs):

    form = forms.ImageForm()

    if request.method == 'POST':
        form = forms.ImageForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect("/successful")

    return render(request, "create.html", dict(form=form))


def dashboard(request, *args, **kwargs):
    return render(request, 'dashboard.html')


def update(request, image_id=None):

    update = get_object_or_404(Image, pk=image_id)

    form = forms.ImageForm(
        request.POST,
        request.FILES,
        instance=update
    )

    if request.method == "POST":
        form = forms.ImageForm(
            request.POST,
            request.FILES,
            instance=update
        )
        if form.is_valid():
            form.save()
            return redirect("imageprocessor:index")

    return render(
        request,
        "edit.html",
        dict(
            update=update,
            form=form
        )
    )


def delete_image(request, image_id=None):

    image_to_delete = get_object_or_404(Image, pk=image_id)

    if request.method == "POST":
        image_to_delete.delete()
        return redirect("imageprocessor:index")

def success(request, *args, **kwargs):
    return render(request, 'success.html')

templates/create.html
{% extends 'index.html' %}


{% block content %}

<form action="{% url 'imageprocessor:create' %}" method="post" enctype="multipart/form-data">
    <!-- here -->
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button" type="submit">Create</button>
</form>
{% endblock %}

templates/dashboard.html
{% extends 'index.html' %}


{% block content %}
<div id="carouselExampleSlidesOnly" class="carousel slide" data-mdb-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img
        src="https://mdbootstrap.com/img/new/slides/041.jpg"
        class="d-block w-100"
        alt="..."
      />
    </div>
    <div class="carousel-item">
      <img
        src="https://mdbootstrap.com/img/new/slides/042.jpg"
        class="d-block w-100"
        alt="..."
      />
    </div>
    <div class="carousel-item">
      <img
        src="https://mdbootstrap.com/img/new/slides/043.jpg"
        class="d-block w-100"
        alt="..."
      />
    </div>
  </div>
</div>
<br>
<a href="{% url 'imageprocessor:index' %}" class="btn btn-success">Home</a>
{% endblock %}

templates/edit.html
{% extends 'index.html' %}


{% block content %}

<form action="{% url 'imageprocessor:update' update.id %}" method="POST" enctype="multipart/form-data">
    <!-- here -->
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button" type="submit">Update</button>
</form>
{% endblock %}

templates/index.html
</html>
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" rel="stylesheet" />
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <!-- MDB -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.css" rel="stylesheet" />
</head>
<!-- online iinks -->
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <!-- Container wrapper -->
            <div class="container-fluid">
                <!-- Toggle button -->
                <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                    data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>

                <!-- Collapsible wrapper -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Navbar brand -->
                    <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'imageprocessor:index' %}">
                        <img src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png" height="15" alt=""
                            loading="lazy" />
                    </a>
                    <!-- Left links -->
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'imageprocessor:dashboard' %}">Dashboard</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" href="{% url 'imageprocessor:create' %}">Register</a>
                        </li>
                    </ul>
                    <!-- Left links -->
                </div>
                <!-- Collapsible wrapper -->

                <!-- Right elements -->
                <div class="d-flex align-items-center">
                    <form class="d-flex input-group w-auto">
                        <input type="search" class="form-control rounded" placeholder="Search" aria-label="Search"
                            aria-describedby="search-addon" />
                        <span class="input-group-text text-white border-0" id="search-addon">
                            <i class="fas fa-search"></i>
                        </span>
                    </form>
                    <!-- Avatar -->
                    <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#"
                        id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
                        <img src="https://mdbootstrap.com/img/new/avatars/2.jpg" class="rounded-circle" height="25"
                            alt="" loading="lazy" />
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
                        <li>
                            <a class="dropdown-item" href="{% url 'imageprocessor:dashboard' %}">My profile</a>
                        </li>
                        <li>
                            <a class="dropdown-item" href="#">Settings</a>
                        </li>
                    </ul>
                </div>
                <!-- Right elements -->
            </div>
            <!-- Container wrapper -->
        </nav>
    </header>
    <!-- Navbar -->

    <main class="main">
        <div class="container">
            {% block content %}
                {% if image %}
                    {% for images in image %}
                        <div class="row">
                            <div class="col-md-4">
                                <img class="post-img" src="{{ images.profileURL }}"
                                class="img-fluid hover-shadow" height="300" width="500">
                            </div>
                            <div class="col-md-4">
                                <img class="post-img" src="{{ images.backgroundURL }}"
                                class="img-fluid hover-shadow" height="300" width="500">
                            </div>
                            <div class="col-md-4">
                                <img class="post-img" src="{{ images.featureURL }}"
                                class="img-fluid hover-shadow" height="300" width="500">
                            </div>
                        </div>
                        <br>
                        <form action="{% url 'imageprocessor:delete_image' images.id %}" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                            <button class="button" type="submit">Delete</button>
                        </form>


                        <a href="{% url 'imageprocessor:update' images.id %}" class="btn btn-danger">update image</a>

                    {% endfor %}
                {% endif %}
            {% endblock %}
        </div>
    </main>

    <footer class="footer text-muted text-center text-lg-start">
          <section
            class="d-flex justify-content-center justify-content-lg-between"
          >
            <!-- Left -->
            <div class="me-5 d-none d-lg-block">
              <span>Get connected with us on social networks:</span>
            </div>
        <!-- Left -->

        <!-- Right -->
        <div>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-facebook-f"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-twitter"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-google"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-instagram"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-linkedin"></i>
          </a>
          <a href="" class="me-4 text-reset">
            <i class="fab fa-github"></i>
          </a>
        </div>
        <!-- Right -->
      </section>
      <!-- Section: Social media -->

      <!-- Section: Links  -->
      <section class="">
        <div class="container text-center text-md-start mt-5">
          <!-- Grid row -->
          <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
              <!-- Content -->
              <h6 class="text-uppercase fw-bold mb-4">
                <i class="fas fa-gem me-3"></i>Company name
              </h6>
              <p>
                Here you can use rows and columns to organize your footer content. Lorem ipsum
                dolor sit amet, consectetur adipisicing elit.
              </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">
                Products
              </h6>
              <p>
                <a href="#!" class="text-reset">kuhmasii</a>
              </p>
              <p>
                <a href="#!" class="text-reset">kuhmasii</a>
              </p>
              <p>
                <a href="#!" class="text-reset">kuhmasii</a>
              </p>
              <p>
                <a href="#!" class="text-reset">kuhmasii</a>
              </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">
                Useful links
              </h6>
              <p>
                <a href="#!" class="text-reset">Pricing</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Settings</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Orders</a>
              </p>
              <p>
                <a href="#!" class="text-reset">Help</a>
              </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
              <!-- Links -->
              <h6 class="text-uppercase fw-bold mb-4">
                Contact
              </h6>
              <p><i class="fas fa-home me-3"></i>UI, university of Ibadan</p>
              <p>
                <i class="fas fa-envelope me-3"></i>
                kuhmasii@gmail.com
              </p>
              <p><i class="fas fa-phone me-3"></i> +234 804 444 4444</p>
              <p><i class="fas fa-print me-3"></i> +234 803 333 3333</p>
            </div>
            <!-- Grid column -->
          </div>
          <!-- Grid row -->
        </div>
      </section>
      <!-- Section: Links  -->

      <!-- Copyright -->
      <div class="text-center p-4" style="background-color: darkgray;">
        © 2021 Copyright:
        <a class="text-reset fw-bold" href="https://mdbootstrap.com/">photo_tutorial.com</a>
      </div>
      <!-- Copyright -->
    </footer>
</body>
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.5.0/mdb.min.js"></script>

</html>

templates/success.html
{% extends 'index.html' %}


{% block content %}
<h2>Your picture is saved in the database.</h2>
<a href="{% url 'imageprocessor:index' %}" class="btn btn-success">Home</a>
{% endblock %}